# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26647654ce3342090450fbcfdb4cd98d1984b5874d6c953dda25704667cff863e4f9eb105bdf34a30b9e4d6802d2f5076cb39e0068dc17b2a176085a0f1d4662

test:
  secret_key_base: b5a8abba996a0ee6c0dcc7ab802f6794a92b375062e858d3b2ce0966c1436cda7cb0cfd3b96e8f77a49b6cdf6af2b87e90b70c72ab883c0ef69e219bb282be0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
